### ISSUE TITLE
自动构建CI

### ISSUE THREAD

**Issue by phith0n** [vulhub/vulhub-org#2]
希望完成如下功能：

1. 每次更新vulhub项目，vulhub-org这边自动重新构建
2. 下载最新的vulhub代码，放在docs/vulhub目录下

现在 vulhub.org 是放在 https://www.netlify.com/ 下在，他本身有个简单的自动构建功能，是直接执行的`npm build`。

**Comment by yywing** [comment]
你这任务描述写的也太不细致了吧。
有几个问题。
1. ./src/environments.json 这个文件哪来的，找了半天没找到，需要ci更新么，还是自动根据 docs/vulhub 生成？
2. docs/vulhub 下都放了些啥？ 是vulhub里的每个项目中的 README.zh-cn.md 和图片是么？
3. 为啥我看不到netlify下现在的这个项目的构建

**Comment by phith0n** [comment]
尴尬了

1. 这个配置文件是手工增加的，不要自动生成
2. docs/vulhub下现在放的只有md和图片，但是考虑到放在git里所以把没用的东西删了。如果不放在git里，那就直接下载完整的vulhub代码就行了。
3. 我要在netlify下拉你进来，发下你的邮箱

**Comment by yywing** [comment]
386542536@qq.com

**Comment by yywing** [comment]
这个配置文件是做啥子的哦（不是一个包含所有漏洞的列表么？），vulhub更新要更改么？

**Comment by yywing** [comment]
> docs/vulhub下现在放的只有md和图片，但是考虑到放在git里所以把没用的东西删了。如果不放在git里，那就直接下载完整的vulhub代码就行了

我看你网站里显示的都是中文的，直接把英文的Readme复制过来？？

**Comment by phith0n** [comment]
./src/environments.json 里面存的就是漏洞标题、目录、CVE号等。每次更新vulhub的这些元信息，就要改这个文件。

但这个文件是需要手工修改的，因为信息没有统一，没法自动生成。

每次更新vulhub都应该触发CI，更新可能有如下情况：

1. 增加了新漏洞
2. 修改了漏洞标题等元信息
3. 修改了README

1、2种情况，我会在修改vulhub后，再来修改vulhub-org这个项目的./src/environments.json文件。第三种情况和这个文件没关系。

----

语言那个没关系，先把自动构建的做好，再考虑怎么自动修改语言。另外还需要等所有环境都有英文文档了才能做，暂时混合着来吧。

**Comment by yywing** [comment]
netlify拉了么？？？

**Comment by phith0n** [comment]
拉了，你没收到么

**Comment by yywing** [comment]
奥奥，收到了

**Comment by yywing** [comment]
https://www.netlify.com/docs/webhooks/#incoming-webhooks
有个这个东西，那就直接在 vulhub 那边加上一个ci curl一下就行了

**Comment by phith0n** [comment]
finished in https://github.com/vulhub/vulhub-org/pull/3
